notifications:
  email: false
git:
  quiet: true
  depth: 1
jdk: openjdk8
language: java
install: true
addons:
  apt:
    packages:
      - jq
      - bash
      - curl
      - sudo
      - lsof
      - unzip
before_install:
  # https://objectcomputing.com/news/2019/01/07/sdkman-travis
  - curl -s get.sdkman.io | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install jbake
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8001 8002 8080 5432
script:
  - jbake -b
  - jbake -s &
  - sleep 3s
  - curl http://127.0.0.1:8820/
  - stop_any 8820
env:
  global:
    secure: OufGE9snTs5494dr9K+daDpdadRwT7mX1dbD90BfUpeZEWbreSdZLCOvy9dcKJUH8Eslq0RSpJ+EQLwLoBey25GJjb16bF/ah/rOOREly7ks/kJZ6ULSOHqOVfCZyB7YZRgojbMaEDLjJI8lmoE3+F6rldaoMc7sRxIeknlPMpcM/VJqBKiCFAiu4bU+3MxXGMKn2RCYgQrKxtoKi5ABzkVtmedqvlkUFGJDhxSu5ZdgIN/EG1w2ETmNk8vQmkU0x/a85rTE6jWkFw/J8Y2sxDt8f9CLDVc1DO2azDCNXnjxAYn+RI5RT8vK/xtSthnXdJKOQ4m3UsJIeDvTt8AzPwxcWKzZTXN/u0gyWFam+779pGKFT9KAXja/3ooj72iXPmZqb7VwC1X+p7rw/6J3cZPWNZWhBHVPx8ObFWMA/1SYqmXW29acJpLjf9f6Yyn3MeP1zTvwA3SRrUlrXp5sBNPy0F3XAOTBqP/uXu+9120uMU+M7NuRYiZd7c+ETV8dbG/ZYix5t+B+3CUaKcwrazcb17sT6pBTBhZV+V5XUn/KOsIl4eQZoUYKik5XJjov2/NUAcQbRODElE9mvlNlitCwRlyUyWnVd7hQoMIYqk5pOWcdVloOrqVYkVoT6Rgjh5c0cRX3PKlXG1e+Sc139WgVjOM6Zs6dJYqFxiC70ss=
before_deploy:
  - rm -rf output
  - jbake -b
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: output
  target_branch: gh-pages
